#
# Pebble build script for "Does It Doom?".
# Vendored Doom source under vendor/doom/ is selectively included by globbing
# only the files we've actually ported (src/c/doom/**/*.c). The unported tree
# stays in vendor/ as a reference and does NOT get compiled until we move
# specific files into src/c/doom/ explicitly.
#
top = '.'
out = 'build'


def options(ctx):
    ctx.load('pebble_sdk')


def configure(ctx):
    ctx.load('pebble_sdk')


def build(ctx):
    ctx.load('pebble_sdk')

    binaries = []

    for p in ctx.env.TARGET_PLATFORMS:
        ctx.set_env(ctx.all_envs[p])
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        ctx.pbl_program(
            source=ctx.path.ant_glob('src/c/**/*.c'),
            target=app_elf,
        )
        binaries.append({'platform': p, 'app_elf': app_elf})

    ctx.set_group('bundle')
    ctx.pbl_bundle(
        binaries=binaries,
        js=ctx.path.ant_glob(['src/pkjs/**/*.js', 'src/pkjs/**/*.json']),
        js_entry_file='src/pkjs/index.js',
    )
