package com.dsugarman.glance;

import android.content.ComponentName;
import android.content.Context;
import android.graphics.Bitmap;
import android.media.MediaMetadata;
import android.media.session.MediaController;
import android.media.session.MediaSessionManager;
import android.media.session.PlaybackState;
import android.os.Handler;
import android.os.Looper;
import android.service.notification.NotificationListenerService;
import android.util.Log;
import com.getpebble.android.kit.PebbleKit;
import com.getpebble.android.kit.util.PebbleDictionary;
import java.util.List;
import java.util.UUID;

public class MediaListenerService extends NotificationListenerService
        implements MediaSessionManager.OnActiveSessionsChangedListener {

    private static final String TAG = "GlanceNP";
    private static final UUID WATCH_UUID =
            UUID.fromString("5b5b6a8e-1f5f-4f6e-9a1f-3b9f1a2c4d5e");

    // AppMessage keys — generated by the Pebble build from package.json
    // messageKeys (see build/js/message_keys.json). Update if you add/reorder.
    private static final int KEY_NOW_TITLE  = 10005;
    private static final int KEY_NOW_ARTIST = 10006;
    private static final int KEY_ART_CHUNK  = 10007;
    private static final int KEY_ART_OFFSET = 10008;
    private static final int KEY_ART_TOTAL  = 10009;

    private MediaSessionManager sessionManager;
    private MediaController activeController;
    private final MediaController.Callback controllerCb = new MediaController.Callback() {
        @Override
        public void onMetadataChanged(MediaMetadata metadata) {
            handleMetadata(metadata);
        }
        @Override
        public void onPlaybackStateChanged(PlaybackState state) {
            if (state == null) return;
            if (state.getState() != PlaybackState.STATE_PLAYING && state.getState() != PlaybackState.STATE_PAUSED) {
                sendCleared();
            }
        }
    };

    private static String lastSentSummary;
    public static String getLastSentSummary() { return lastSentSummary; }

    @Override
    public void onListenerConnected() {
        super.onListenerConnected();
        sessionManager = (MediaSessionManager) getSystemService(Context.MEDIA_SESSION_SERVICE);
        ComponentName self = new ComponentName(this, MediaListenerService.class);
        try {
            sessionManager.addOnActiveSessionsChangedListener(this, self);
            onActiveSessionsChanged(sessionManager.getActiveSessions(self));
        } catch (SecurityException e) {
            Log.e(TAG, "MediaSession permission denied", e);
        }
    }

    @Override
    public void onListenerDisconnected() {
        if (sessionManager != null) {
            sessionManager.removeOnActiveSessionsChangedListener(this);
        }
        detachController();
        super.onListenerDisconnected();
    }

    @Override
    public void onActiveSessionsChanged(List<MediaController> controllers) {
        detachController();
        if (controllers == null || controllers.isEmpty()) {
            sendCleared();
            return;
        }
        activeController = controllers.get(0);
        activeController.registerCallback(controllerCb);
        handleMetadata(activeController.getMetadata());
    }

    private void detachController() {
        if (activeController != null) {
            try { activeController.unregisterCallback(controllerCb); } catch (Throwable ignored) {}
            activeController = null;
        }
    }

    private void handleMetadata(MediaMetadata metadata) {
        if (metadata == null) { sendCleared(); return; }
        String title = metadata.getString(MediaMetadata.METADATA_KEY_TITLE);
        String artist = metadata.getString(MediaMetadata.METADATA_KEY_ARTIST);
        if (artist == null) artist = metadata.getString(MediaMetadata.METADATA_KEY_ALBUM_ARTIST);
        Bitmap art = metadata.getBitmap(MediaMetadata.METADATA_KEY_ALBUM_ART);
        if (art == null) art = metadata.getBitmap(MediaMetadata.METADATA_KEY_ART);
        if (art == null) art = metadata.getBitmap(MediaMetadata.METADATA_KEY_DISPLAY_ICON);

        sendText(title == null ? "" : title, artist == null ? "" : artist);
        if (art != null) sendArt(art);

        lastSentSummary = (title == null ? "(no title)" : title)
                + (artist == null || artist.isEmpty() ? "" : " — " + artist)
                + (art == null ? "  [no art]" : "  [art " + art.getWidth() + "x" + art.getHeight() + "]");
    }

    private void sendCleared() {
        sendText("", "");
        lastSentSummary = "(nothing playing)";
    }

    private void sendText(String title, String artist) {
        if (!PebbleKit.isWatchConnected(this)) return;
        PebbleDictionary dict = new PebbleDictionary();
        dict.addString(KEY_NOW_TITLE, truncate(title, 40));
        dict.addString(KEY_NOW_ARTIST, truncate(artist, 40));
        PebbleKit.sendDataToPebble(this, WATCH_UUID, dict);
    }

    private Thread artTxThread;

    /**
     * Sends the palette-encoded art bitmap as a sequence of ~500-byte AppMessage
     * chunks. The watch reassembles by offset and validates the declared total.
     *
     * Only one transfer runs at a time. A new call interrupts the previous
     * thread before kicking off its own — without that, concurrent transfers
     * race on the watch's shared art buffer and produce a frame stitched
     * together from two different covers (horizontal stripes).
     */
    private void sendArt(final Bitmap art) {
        if (!PebbleKit.isWatchConnected(this)) return;
        final byte[] encoded = PebblePaletteEncoder.encode(art);
        Thread prev = artTxThread;
        if (prev != null && prev.isAlive()) {
            prev.interrupt();
            try { prev.join(300); } catch (InterruptedException ignored) {}
        }
        artTxThread = new Thread(new Runnable() {
            @Override
            public void run() {
                final int CHUNK = 500;
                for (int offset = 0; offset < encoded.length; offset += CHUNK) {
                    if (Thread.currentThread().isInterrupted()) return;
                    int end = Math.min(offset + CHUNK, encoded.length);
                    byte[] piece = new byte[end - offset];
                    System.arraycopy(encoded, offset, piece, 0, piece.length);
                    PebbleDictionary dict = new PebbleDictionary();
                    dict.addBytes(KEY_ART_CHUNK, piece);
                    dict.addUint16(KEY_ART_OFFSET, (short) offset);
                    dict.addUint16(KEY_ART_TOTAL, (short) encoded.length);
                    PebbleKit.sendDataToPebble(MediaListenerService.this, WATCH_UUID, dict);
                    try { Thread.sleep(120); } catch (InterruptedException e) { return; }
                }
            }
        }, "glance-art-tx");
        artTxThread.start();
    }

    private static String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() <= max ? s : s.substring(0, max);
    }
}
