package com.dsugarman.glance;

import android.Manifest;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.os.Build;
import android.media.MediaMetadata;
import android.media.session.MediaController;
import android.media.session.MediaSessionManager;
import android.media.session.PlaybackState;
import android.os.Handler;
import android.os.Looper;
import android.service.notification.NotificationListenerService;
import android.util.Log;
import com.getpebble.android.kit.PebbleKit;
import com.getpebble.android.kit.util.PebbleDictionary;
import java.util.List;
import java.util.UUID;

public class MediaListenerService extends NotificationListenerService
        implements MediaSessionManager.OnActiveSessionsChangedListener {

    private static final String TAG = "GlanceNP";
    private static final UUID WATCH_UUID =
            UUID.fromString("5b5b6a8e-1f5f-4f6e-9a1f-3b9f1a2c4d5e");

    // AppMessage keys — generated by the Pebble build from package.json
    // messageKeys (see build/js/message_keys.json). Update if you add/reorder.
    private static final int KEY_NOW_TITLE       = 10005;
    private static final int KEY_NOW_ARTIST      = 10006;
    private static final int KEY_ART_CHUNK       = 10007;
    private static final int KEY_ART_OFFSET      = 10008;
    private static final int KEY_ART_TOTAL       = 10009;
    private static final int KEY_REQUEST_REFRESH = 10014;

    private MediaSessionManager sessionManager;
    private MediaController activeController;
    private PebbleKit.PebbleDataReceiver dataReceiver;
    // Second receiver for the standalone metronome watchapp. It runs in the
    // same process so it inherits this service's elevated background status,
    // which is what lets MetronomeService start as a foreground service when
    // the metronome app opens on the watch.
    private PebbleKit.PebbleDataReceiver metronomeReceiver;
    private final MediaController.Callback controllerCb = new MediaController.Callback() {
        @Override
        public void onMetadataChanged(MediaMetadata metadata) {
            handleMetadata(metadata);
        }
        @Override
        public void onPlaybackStateChanged(PlaybackState state) {
            if (state == null) return;
            if (state.getState() == PlaybackState.STATE_PLAYING) {
                // Resume from pause: re-send so the watch wipes back to the cover.
                if (activeController != null) handleMetadata(activeController.getMetadata());
            } else {
                sendCleared();
            }
        }
    };

    private static String lastSentSummary;
    public static String getLastSentSummary() { return lastSentSummary; }

    @Override
    public void onListenerConnected() {
        super.onListenerConnected();
        sessionManager = (MediaSessionManager) getSystemService(Context.MEDIA_SESSION_SERVICE);
        ComponentName self = new ComponentName(this, MediaListenerService.class);
        try {
            sessionManager.addOnActiveSessionsChangedListener(this, self);
            onActiveSessionsChanged(sessionManager.getActiveSessions(self));
        } catch (SecurityException e) {
            Log.e(TAG, "MediaSession permission denied", e);
        }
        // Listen for the watchapp's REQUEST_REFRESH so we can re-push current
        // playback state after a watchface restart. Without this, restarts
        // (e.g. the user clearing notifications on the Pebble) wipe the
        // displayed track and the Android side has no signal to resend.
        //
        // We can't use PebbleKit.registerReceivedDataHandler — it calls
        // registerReceiver without RECEIVER_EXPORTED/NOT_EXPORTED, which
        // throws SecurityException on Android 14+. Register ourselves with
        // the same intent action and pass the flag explicitly.
        dataReceiver = new PebbleKit.PebbleDataReceiver(WATCH_UUID) {
            @Override
            public void receiveData(Context ctx, int transId, PebbleDictionary data) {
                PebbleKit.sendAckToPebble(ctx, transId);
                if (data.contains(KEY_REQUEST_REFRESH)) {
                    PlaybackState ps = activeController == null ? null : activeController.getPlaybackState();
                    if (ps != null && ps.getState() == PlaybackState.STATE_PLAYING) {
                        handleMetadata(activeController.getMetadata());
                    } else {
                        sendCleared();
                    }
                    // Refresh the metronome chip on Glance from cached prefs
                    // (avoids waking MetronomeService just to read the value).
                    pushMetronomeMinutesToGlance(ctx);
                }
            }
        };
        registerReceiver(dataReceiver,
                new IntentFilter("com.getpebble.action.app.RECEIVE"),
                Context.RECEIVER_EXPORTED);

        metronomeReceiver = new PebbleKit.PebbleDataReceiver(MetronomeService.METRONOME_UUID) {
            @Override
            public void receiveData(Context ctx, int transId, PebbleDictionary data) {
                PebbleKit.sendAckToPebble(ctx, transId);
                dispatchToMetronomeService(ctx, data);
            }
        };
        registerReceiver(metronomeReceiver,
                new IntentFilter("com.getpebble.action.app.RECEIVE"),
                Context.RECEIVER_EXPORTED);

        // Glance also receives this listener's pings — if the Glance app is
        // showing it wants today's metronome minutes too. The metronome
        // service owns the source of truth (SharedPreferences); we read it
        // statically here so we don't have to wake the service for a query.
        // The Glance REQUEST_REFRESH branch above is the trigger.
    }

    private static void dispatchToMetronomeService(Context ctx, PebbleDictionary data) {
        // Wrap the whole body so a malformed dict (e.g. a key with an
        // unexpected uint vs int storage type — see PebbleDictTypeException)
        // can't tear down the entire app from inside a BroadcastReceiver.
        Intent send = null;
        try {
            // Each getInteger call throws if the key is present *with the
            // wrong storage type*, so we only call it for keys the watchapp
            // writes as int32. OPEN/CLOSE/TICK_*/BPM are all int32. The
            // bundled TODAY_MINUTES_REQUEST on watch is a uint8 — and is
            // redundant when OPEN is also present (OPEN already triggers a
            // totals push), so we just ignore it on this path.
            Long opened  = data.contains(MetronomeService.KEY_METRONOME_OPENED)
                           ? data.getInteger(MetronomeService.KEY_METRONOME_OPENED) : null;
            Long closed  = data.contains(MetronomeService.KEY_METRONOME_CLOSED)
                           ? data.getInteger(MetronomeService.KEY_METRONOME_CLOSED) : null;
            Long tickOn  = data.contains(MetronomeService.KEY_TICK_STARTED)
                           ? data.getInteger(MetronomeService.KEY_TICK_STARTED) : null;
            Long tickOff = data.contains(MetronomeService.KEY_TICK_STOPPED)
                           ? data.getInteger(MetronomeService.KEY_TICK_STOPPED) : null;
            Long bpm     = data.contains(MetronomeService.KEY_BPM_CHANGED)
                           ? data.getInteger(MetronomeService.KEY_BPM_CHANGED) : null;

            if (opened != null) {
                send = serviceIntent(ctx, MetronomeService.EVT_OPENED, opened.intValue());
            } else if (closed != null) {
                send = serviceIntent(ctx, MetronomeService.EVT_CLOSED, 0);
            } else if (tickOn != null) {
                send = serviceIntent(ctx, MetronomeService.EVT_TICK_ON, tickOn.intValue());
            } else if (tickOff != null) {
                send = serviceIntent(ctx, MetronomeService.EVT_TICK_OFF, 0);
            } else if (bpm != null) {
                send = serviceIntent(ctx, MetronomeService.EVT_BPM, bpm.intValue());
            }
        } catch (Throwable t) {
            Log.e(TAG, "metronome dict decode failed", t);
            return;
        }
        if (send == null) return;

        // Hard gate on RECORD_AUDIO. Without it, MetronomeService can't
        // promote to a microphone-type foreground service — on Android 14+
        // the platform kills the process with ForegroundServiceDidNotStartIn
        // TimeException about 5 sec after startForegroundService(). The user
        // grants mic from the Glance NP main screen.
        if (ctx.checkSelfPermission(Manifest.permission.RECORD_AUDIO)
                != PackageManager.PERMISSION_GRANTED) {
            Log.w(TAG, "metronome event received but RECORD_AUDIO not granted; ignoring");
            return;
        }

        // Trampoline through MetronomeTriggerActivity instead of starting
        // the service directly. Android 14+ refuses microphone-type FGS
        // unless the calling app is in TOP / while-in-use state, and a
        // BroadcastReceiver is BFGS — not TOP. The Activity briefly is.
        try {
            Intent activityIntent = new Intent(ctx, MetronomeTriggerActivity.class);
            activityIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            activityIntent.putExtras(send.getExtras());
            ctx.startActivity(activityIntent);
        } catch (Throwable t) {
            Log.e(TAG, "metronome trampoline activity start failed", t);
        }
    }

    private static Intent serviceIntent(Context ctx, String evt, int value) {
        Intent i = new Intent(ctx, MetronomeService.class);
        i.putExtra(MetronomeService.EXTRA_EVENT, evt);
        i.putExtra(MetronomeService.EXTRA_VALUE, value);
        return i;
    }

    private static void pushMetronomeMinutesToGlance(Context ctx) {
        if (!PebbleKit.isWatchConnected(ctx)) return;
        int mins = MetronomeService.peekTodayMinutes(ctx);
        PebbleDictionary d = new PebbleDictionary();
        d.addInt32(MetronomeService.KEY_GLANCE_METRONOME_MINUTES, mins);
        PebbleKit.sendDataToPebble(ctx, WATCH_UUID, d);
    }

    @Override
    public void onListenerDisconnected() {
        if (sessionManager != null) {
            sessionManager.removeOnActiveSessionsChangedListener(this);
        }
        if (dataReceiver != null) {
            try { unregisterReceiver(dataReceiver); } catch (Throwable ignored) {}
            dataReceiver = null;
        }
        if (metronomeReceiver != null) {
            try { unregisterReceiver(metronomeReceiver); } catch (Throwable ignored) {}
            metronomeReceiver = null;
        }
        detachController();
        super.onListenerDisconnected();
    }

    @Override
    public void onActiveSessionsChanged(List<MediaController> controllers) {
        detachController();
        if (controllers == null || controllers.isEmpty()) {
            sendCleared();
            return;
        }
        activeController = controllers.get(0);
        activeController.registerCallback(controllerCb);
        handleMetadata(activeController.getMetadata());
    }

    private void detachController() {
        if (activeController != null) {
            try { activeController.unregisterCallback(controllerCb); } catch (Throwable ignored) {}
            activeController = null;
        }
    }

    private void handleMetadata(MediaMetadata metadata) {
        if (metadata == null) { sendCleared(); return; }
        // Only push current-track data if playback is actively playing. Paused
        // sessions retain metadata indefinitely; without this guard a stray
        // onMetadataChanged after pause re-pushes the album art and the
        // watchface flips off the default photo right after we cleared it.
        if (activeController != null) {
            PlaybackState ps = activeController.getPlaybackState();
            if (ps == null) {
                // State not yet populated (e.g. just-attached session after a
                // listener reconnect). Wait for onPlaybackStateChanged — don't
                // pre-emptively clear, that would strand us with default art
                // until the next genuine state transition.
                return;
            }
            if (ps.getState() != PlaybackState.STATE_PLAYING) {
                sendCleared();
                return;
            }
        }
        String title = metadata.getString(MediaMetadata.METADATA_KEY_TITLE);
        String artist = metadata.getString(MediaMetadata.METADATA_KEY_ARTIST);
        if (artist == null) artist = metadata.getString(MediaMetadata.METADATA_KEY_ALBUM_ARTIST);
        Bitmap art = metadata.getBitmap(MediaMetadata.METADATA_KEY_ALBUM_ART);
        if (art == null) art = metadata.getBitmap(MediaMetadata.METADATA_KEY_ART);
        if (art == null) art = metadata.getBitmap(MediaMetadata.METADATA_KEY_DISPLAY_ICON);

        sendText(title == null ? "" : title, artist == null ? "" : artist);
        if (art != null) sendArt(art);

        lastSentSummary = (title == null ? "(no title)" : title)
                + (artist == null || artist.isEmpty() ? "" : " — " + artist)
                + (art == null ? "  [no art]" : "  [art " + art.getWidth() + "x" + art.getHeight() + "]");
    }

    private void sendCleared() {
        sendText("", "");
        lastSentSummary = "(nothing playing)";
    }

    private void sendText(String title, String artist) {
        if (!PebbleKit.isWatchConnected(this)) return;
        PebbleDictionary dict = new PebbleDictionary();
        dict.addString(KEY_NOW_TITLE, truncate(title, 40));
        dict.addString(KEY_NOW_ARTIST, truncate(artist, 40));
        PebbleKit.sendDataToPebble(this, WATCH_UUID, dict);
    }

    private Thread artTxThread;

    /**
     * Sends the palette-encoded art bitmap as a sequence of ~500-byte AppMessage
     * chunks. The watch reassembles by offset and validates the declared total.
     *
     * Only one transfer runs at a time. A new call interrupts the previous
     * thread before kicking off its own — without that, concurrent transfers
     * race on the watch's shared art buffer and produce a frame stitched
     * together from two different covers (horizontal stripes).
     */
    private void sendArt(final Bitmap art) {
        if (!PebbleKit.isWatchConnected(this)) return;
        final byte[] encoded = PebblePaletteEncoder.encode(art);
        Thread prev = artTxThread;
        if (prev != null && prev.isAlive()) {
            prev.interrupt();
            try { prev.join(300); } catch (InterruptedException ignored) {}
        }
        artTxThread = new Thread(new Runnable() {
            @Override
            public void run() {
                final int CHUNK = 500;
                for (int offset = 0; offset < encoded.length; offset += CHUNK) {
                    if (Thread.currentThread().isInterrupted()) return;
                    int end = Math.min(offset + CHUNK, encoded.length);
                    byte[] piece = new byte[end - offset];
                    System.arraycopy(encoded, offset, piece, 0, piece.length);
                    PebbleDictionary dict = new PebbleDictionary();
                    dict.addBytes(KEY_ART_CHUNK, piece);
                    dict.addUint16(KEY_ART_OFFSET, (short) offset);
                    dict.addUint16(KEY_ART_TOTAL, (short) encoded.length);
                    PebbleKit.sendDataToPebble(MediaListenerService.this, WATCH_UUID, dict);
                    try { Thread.sleep(120); } catch (InterruptedException e) { return; }
                }
            }
        }, "glance-art-tx");
        artTxThread.start();
    }

    private static String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() <= max ? s : s.substring(0, max);
    }
}
